export type DFCSourceType = 'dre' | 'asset' | 'liability' | 'equity' | 'cash';
export type DFCDisplayType = 'item' | 'result';

export interface DFCLineDefinition {
    key: string;
    label: string;
    section: string;
    order: number;
    displayType: DFCDisplayType;
    configurable: boolean;
    visibleInReport: boolean;
    sourceType?: DFCSourceType;
    consolidatedInto?: string;
    defaultMultiplier?: number;
    includeChildrenByDefault?: boolean;
    description?: string;
}

export interface DFCReportRowDefinition {
    type: 'section' | 'line' | 'separator';
    label?: string;
    key?: string;
}

export const DFC_LINE_DEFINITIONS: DFCLineDefinition[] = [
    {
        key: 'resultadoLiquidoExercicio',
        label: 'Resultado Líquido do Exercício',
        section: 'resultado_contabil',
        order: 10,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'depreciacaoAmortizacao',
        label: 'Depreciação e Amortização',
        section: 'resultado_contabil',
        order: 20,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'resultadoVendaAtivoImobilizado',
        label: 'Resultado da Venda de Ativo Imobilizado',
        section: 'resultado_contabil',
        order: 30,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: -1,
        includeChildrenByDefault: true,
    },
    {
        key: 'resultadoEquivalenciaPatrimonial',
        label: 'Resultado da Equivalência Patrimonial',
        section: 'resultado_contabil',
        order: 40,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'recebimentosLucrosDividendosSubsidiarias',
        label: 'Recebimentos de Lucros e Dividendos de Subsidiárias',
        section: 'resultado_contabil',
        order: 50,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'lucroAjustado',
        label: 'Lucro Ajustado',
        section: 'resultado_contabil',
        order: 60,
        displayType: 'result',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'contasAReceber',
        label: 'Contas a Receber',
        section: 'variacao_ativo',
        order: 70,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'adiantamentos',
        label: 'Adiantamentos',
        section: 'variacao_ativo',
        order: 80,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'impostosCompensar',
        label: 'Impostos a Compensar',
        section: 'variacao_ativo',
        order: 90,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'estoques',
        label: 'Estoques',
        section: 'variacao_ativo',
        order: 100,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'despesasAntecipadas',
        label: 'Despesas Antecipadas',
        section: 'variacao_ativo',
        order: 110,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'outrasContasReceber',
        label: 'Outras Contas a Receber',
        section: 'variacao_ativo',
        order: 120,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'asset',
        consolidatedInto: 'variacaoAtivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'fornecedores',
        label: 'Fornecedores',
        section: 'variacao_passivo',
        order: 130,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'liability',
        consolidatedInto: 'variacaoPassivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'obrigacoesTrabalhistas',
        label: 'Obrigações Trabalhistas',
        section: 'variacao_passivo',
        order: 140,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'liability',
        consolidatedInto: 'variacaoPassivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'obrigacoesTributarias',
        label: 'Obrigações Tributárias',
        section: 'variacao_passivo',
        order: 150,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'liability',
        consolidatedInto: 'variacaoPassivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'outrasObrigacoes',
        label: 'Outras Obrigações',
        section: 'variacao_passivo',
        order: 160,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'liability',
        consolidatedInto: 'variacaoPassivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'parcelamentos',
        label: 'Parcelamentos',
        section: 'variacao_passivo',
        order: 170,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'liability',
        consolidatedInto: 'variacaoPassivo',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'variacaoAtivo',
        label: 'Variação Ativo',
        section: 'operacional',
        order: 180,
        displayType: 'item',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'variacaoPassivo',
        label: 'Variação Passivo',
        section: 'operacional',
        order: 190,
        displayType: 'item',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'resultadoOperacional',
        label: 'Resultado Operacional',
        section: 'operacional',
        order: 200,
        displayType: 'result',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'recebimentosVendasAtivo',
        label: 'Recebimentos por Vendas de Ativo Inv./Imob./Intang.',
        section: 'investimentos',
        order: 210,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'comprasImobilizado',
        label: 'Compras de Imobilizado',
        section: 'investimentos',
        order: 220,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'asset',
        defaultMultiplier: -1,
        includeChildrenByDefault: true,
    },
    {
        key: 'aquisicoesInvestimentos',
        label: 'Aquisições em Investimentos',
        section: 'investimentos',
        order: 230,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'asset',
        defaultMultiplier: -1,
        includeChildrenByDefault: true,
    },
    {
        key: 'baixaAtivoImobilizado',
        label: 'Baixa de Ativo Imobilizado',
        section: 'investimentos',
        order: 240,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'dre',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'resultadoInvestimento',
        label: 'Resultado de Investimento',
        section: 'investimentos',
        order: 250,
        displayType: 'result',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'integralizacaoCapitalSocial',
        label: 'Integralização ou Aumento de Capital Social',
        section: 'financiamentos',
        order: 260,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'equity',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'pagamentoLucrosDividendos',
        label: 'Pagamento de Lucros e Dividendos',
        section: 'financiamentos',
        order: 270,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'liability',
        defaultMultiplier: -1,
        includeChildrenByDefault: true,
    },
    {
        key: 'variacaoEmprestimosFinanciamentos',
        label: 'Variação em Empréstimos/Financiamentos',
        section: 'financiamentos',
        order: 280,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'liability',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'dividendosProvisionadosPagar',
        label: 'Dividendos Provisionados a Pagar',
        section: 'financiamentos',
        order: 290,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'liability',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'variacaoEmprestimosPessoasLigadas',
        label: 'Variação Empréstimos Pessoas Ligadas PJ/PF',
        section: 'financiamentos',
        order: 300,
        displayType: 'item',
        configurable: true,
        visibleInReport: true,
        sourceType: 'liability',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
    },
    {
        key: 'resultadoFinanceiro',
        label: 'Resultado Financeiro',
        section: 'financiamentos',
        order: 310,
        displayType: 'result',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'disponibilidadesBase',
        label: 'Disponibilidades Base',
        section: 'base_caixa',
        order: 320,
        displayType: 'item',
        configurable: true,
        visibleInReport: false,
        sourceType: 'cash',
        defaultMultiplier: 1,
        includeChildrenByDefault: true,
        description: 'Base para saldo inicial/final disponível da DFC.',
    },
    {
        key: 'saldoInicialDisponivel',
        label: 'Saldo Inicial Disponível',
        section: 'geracao_caixa',
        order: 330,
        displayType: 'item',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'saldoFinalDisponivel',
        label: 'Saldo Final Disponível',
        section: 'geracao_caixa',
        order: 340,
        displayType: 'item',
        configurable: false,
        visibleInReport: true,
    },
    {
        key: 'resultadoGeracaoCaixa',
        label: 'Resultado Geração de Caixa',
        section: 'geracao_caixa',
        order: 350,
        displayType: 'result',
        configurable: false,
        visibleInReport: true,
    },
];

export const DFC_REPORT_ROWS: DFCReportRowDefinition[] = [
    { type: 'section', label: 'Resultado Contábil' },
    { type: 'line', key: 'resultadoLiquidoExercicio' },
    { type: 'line', key: 'depreciacaoAmortizacao' },
    { type: 'line', key: 'resultadoVendaAtivoImobilizado' },
    { type: 'line', key: 'resultadoEquivalenciaPatrimonial' },
    { type: 'line', key: 'recebimentosLucrosDividendosSubsidiarias' },
    { type: 'line', key: 'lucroAjustado' },
    { type: 'separator' },
    { type: 'section', label: 'Fluxos de Caixa Originários de Atividades Operacionais' },
    { type: 'line', key: 'variacaoAtivo' },
    { type: 'line', key: 'variacaoPassivo' },
    { type: 'line', key: 'resultadoOperacional' },
    { type: 'separator' },
    { type: 'section', label: 'Fluxos de Caixa Originários de Atividades de Investimentos' },
    { type: 'line', key: 'recebimentosVendasAtivo' },
    { type: 'line', key: 'comprasImobilizado' },
    { type: 'line', key: 'aquisicoesInvestimentos' },
    { type: 'line', key: 'baixaAtivoImobilizado' },
    { type: 'line', key: 'resultadoInvestimento' },
    { type: 'separator' },
    { type: 'section', label: 'Fluxos de Caixa Originários de Atividades de Financiamentos' },
    { type: 'line', key: 'integralizacaoCapitalSocial' },
    { type: 'line', key: 'pagamentoLucrosDividendos' },
    { type: 'line', key: 'variacaoEmprestimosFinanciamentos' },
    { type: 'line', key: 'dividendosProvisionadosPagar' },
    { type: 'line', key: 'variacaoEmprestimosPessoasLigadas' },
    { type: 'line', key: 'resultadoFinanceiro' },
    { type: 'separator' },
    { type: 'section', label: 'Resultado da Geração de Caixa' },
    { type: 'line', key: 'saldoInicialDisponivel' },
    { type: 'line', key: 'saldoFinalDisponivel' },
    { type: 'line', key: 'resultadoGeracaoCaixa' },
];

export const getDfcLineDefinition = (key: string) =>
    DFC_LINE_DEFINITIONS.find((line) => line.key === key);

export const getConfigurableDfcLines = () =>
    DFC_LINE_DEFINITIONS
        .filter((line) => line.configurable)
        .sort((a, b) => a.order - b.order);

export const getVisibleDfcLines = () =>
    DFC_LINE_DEFINITIONS
        .filter((line) => line.visibleInReport)
        .sort((a, b) => a.order - b.order);
